import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({});

const outfitMono = Outfit({});

export const metadata: Metadata = {
  title: "BHASHA GPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit} ${outfitMono} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
